### ISSUE TITLE
Synology docker client displays no packages

### ISSUE THREAD

**Issue by bserem** [willdurand/container-registry-proxy#7]
Thanks for this package, I like the idea of being able to use the synology-ui for things (I find it ok for my simple needs).

I can't get results back though, and here I am raising this issue!

I did all the steps as described in the readme for synology.
- Using host network
- Using an access token with `read:packages` scope
- Using default config for ip/port

I can start `container-registry-proxy` and I see no issues in the logs (from synology UI):
```
2023/05/17 14:06:25 starting container registry proxy on 127.0.0.1:10000
```

I get no results from the registry though:
![image](https://github.com/willdurand/container-registry-proxy/assets/520237/f59cac83-b732-4449-8079-f958f88fa8c3)

The same is true if I search for a package (eg `timetagger` https://github.com/almarklein/timetagger/pkgs/container/timetagger/87459455?tag=latest)

Did I miss something or did something change on githubs side and things stopped working?

Thanks

**Comment by k-s-s** [comment]
Same for me

**Comment by scr3wdriv3r** [comment]
Still no solution? :(

**Comment by willdurand** [comment]
Sorry for the delay. The proxy works for me, I just verified.

Do you see any logs for the proxy container? For example, after the log statement you mentioned, I see:

```
 GET /v2/ -> https://ghcr.io
```

This is Synology talking to the proxy service.

**Comment by scr3wdriv3r** [comment]
Just for check, i test internally the interface 127.0.0.1 with package installer and returns
date,stream,content
2023/10/13 17:50:39,stdout,2023/10/13 14:50:39 POST / -> https://ghcr.io
2023/10/13 17:50:39,stdout,2023/10/13 14:50:39 GET /?package_update_channel=beta&unique=synology_geminilake_720%2B&build=64570&language=enu&major=7&micro=0&arch=geminilake&minor=2&timezone=Athens&nano=3 -> https://ghcr.io
So you can see my syno version.
But with docker registry no logs appear, is blank, but is accepted, no error returned neither in registry interface.

**Comment by willdurand** [comment]
@scr3wdriv3r you edited the content of `/var/packages/Docker/etc/registry.json` as described in the README file, right?

**Comment by deraw** [comment]
> @scr3wdriv3r you edited the content of `/var/packages/Docker/etc/registry.json` as described in the README file, right?

Hi @willdurand @scr3wdriv3r,
The name of the package has changed from `Docker` to `ContainerManager`, that may be the cause

**Comment by scr3wdriv3r** [comment]
> @scr3wdriv3r you edited the content of `/var/packages/Docker/etc/registry.json` as described in the README file, right?
Of course (is not selected as i cannot use it). And yes is DSM v7
![image](https://github.com/willdurand/container-registry-proxy/assets/94255275/ac8d218f-a7b3-49a5-8ddf-e15ceb7038ee)

**Comment by willdurand** [comment]
> The name of the package has changed from `Docker` to `ContainerManager`, that may be the cause

Thanks, I didn't know that because this is still `Docker`for me (even on DSM 7+).

According to @scr3wdriv3r's screenshot, it looks like the config is correct. @scr3wdriv3r can you switch to `GitHubProxy` and see if there are logs? At the very least, Synology is supposed to call it. That there is no result is different.

**Comment by willdurand** [comment]
well, I am sorry to hear that. If there is no log, it means the Synology Docker integration doesn't contact the repository when you browse the list of available images, which seems odd to me.  Since this seems to affect more than just you, I am guessing there is a bug somewhere but I cannot reproduce at the moment and, without more information from affected environments, there isn't a lot of things I can do.

**Comment by aniceberg** [comment]
I am having the same issue of seeing a blank registry. 

I'm using DSM 7.2.1 where there's **ContainerManager** instead of Docker-- so instead of editing `/var/packages/Docker/etc/registry.json` which doesn't exist, I edited the "nas.local" entry found in `/var/packages/ContainerManager/etc/registry.json`

**Comment by FrankSchoene** [comment]
Exactly the same Here. Would be really great to find a solution. How can we Help?

**Comment by vintagesucks** [comment]
This may be obvious to most, but I also had an empty list and no logs until I actually pushed an image to the GitHub container registry. 😅

Working great now, using DSM 7.2.1 and `ContainerManager` instead of `Docker`.

**Comment by akinfold** [comment]
Proxy uses ListPackages to get available packages from github https://github.com/willdurand/container-registry-proxy/blob/main/main.go#L73 and according to documentation it "will list packages for the authenticated user" https://pkg.go.dev/github.com/google/go-github/v57/github#UsersService.ListPackages
I gues, thats why you have empty list in ContainerManager UI until push any package to ghcr.io. @willdurand honestly warned that the proxy solves "a specific use case" with private application.

**Comment by willdurand** [comment]
Ha, indeed. I didn't even consider this but that's a good call, @akinfold. Knowing what the user authenticated with the `GITHUB_TOKEN` personal token has access to would be a good debugging step. It might be possible to do so with cURL:

```
$ curl -L \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer <GITHUB_TOKEN>" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  "https://api.github.com/users/USERNAME/packages?package_type=container"
```

**Comment by mithkr** [comment]
I have the same issue with empty list. Executing the above curl command with my token shows  also a empty list:
 ```
DS224plus:~$ curl -L   -H "Accept: application/vnd.github+json"   -H "Authorization: Bearer <myToken>   -H "X-GitHub-Api-Version: 2022-11-28"   "https://api.github.com/user/packages?package_type=container"
[

]

```

**Comment by willdurand** [comment]
At least this is consistent... @mithkr do you have any (private) container images at https://github.com/mithkr?tab=packages?

**Comment by mithkr** [comment]
No I have no own container images uploaded to github

**Comment by willdurand** [comment]
so that's why there is nothing in Synology's DSM. Now my question is: what did you expect to see listed here?

**Comment by k-s-s** [comment]
Hi
I'm also looking primarily for public images, such as UpSnap:
https://github.com/seriousm4x/UpSnap/pkgs/container/upsnap
Is there anything I can change to view public images?

**Comment by mithkr** [comment]
I have tried following curl command to get the container packages list of an organization e.g. https://github.com/orgs/fhem/packages
curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer <myToken>" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/orgs/fhem/packages?package_type=container
and this return the list. Is there workaround possible by using an other URL in the registry for to get the list from know orgs. Than for the interest org I have than to created dedicated registry in synology container manager

**Comment by willdurand** [comment]
There is no workaround at the moment, unfortunately.

This would need to be added as a new feature, I guess, e.g. by introducing a new environment variable (`GITHUB_PACKAGES_OWNER` maybe?) that we'd use here: https://github.com/willdurand/container-registry-proxy/blob/04d0daf448c62245ebb80d8867b5009e1b92cded/main.go#L73C38-L73C38

**Comment by indermuehle** [comment]
I thought one could access public

**Comment by hedrickbt** [comment]
I am seeing the following URL coming from the "Container Manager" app that replaced the Docker app.  That url, and the only url, happens after I add the new registry and click the refresh button.

2024/02/05 04:41:26 GET /v1/search?q=library/&n=50&page=1 -> https://ghcr.io

I don't see anything in the main.go that handles /v1/search?...

Synology Version: DSM 7.2.1-69057 Update 3
Model: DS920+
Container Manger Version: 20.10.23-1437

**Comment by hedrickbt** [comment]
I have created a pull request to allow non-self packages via a new environment variable GITHUB_USERS.

Details: https://github.com/willdurand/container-registry-proxy/pull/19

Docker container to test/validate
hedrickbt/container-registry-proxy:main.bth
https://hub.docker.com/repository/docker/hedrickbt/container-registry-proxy/general

This works for Synology ContainerManager.  Not sure about Docker, I would need someone to test still has the Docker app.

**Comment by willdurand** [comment]
I landed a change to introduce a new env var as described in https://github.com/willdurand/container-registry-proxy/issues/7#issuecomment-1891695829. Please test but it should resolve some of the issues mentioned here, especially for @k-s-s and @mithkr.

This doesn't allow to query packages from multiple owners at once, which is a different feature. That is proposed in #19 and I'll get back to it when I have an opinion on it.

**Comment by hedrickbt** [comment]
Thank you Will.  This is a great start.  Unfortunately I already need access to 2 different owner repos.  This solution does not work for me.  I would have to run multiple containers and have multiple repo entries in the NAS.Sent from my iPhoneOn Apr 21, 2024, at 12:44 AM, William Durand ***@***.***> wrote:﻿
I landed a change to introduce a new env var as described in #7 (comment). Please test but it should resolve some of the issues mentioned here, especially for @k-s-s and @mithkr.
This doesn't allow to query packages from multiple owners at once, which is a different feature. That is proposed in #19 and I'll get back to it when I have an opinion on it.
